import { User } from './types';

export const SECURITY_QUESTIONS = [
  'Quyển sách bạn thích nhất tên là gì?',
  'Mẹ bạn tên gì?',
  'Tên con vật đầu tiên bạn nuôi là gì?',
  'Trường cấp 1 của bạn tên gì?',
  'Món ăn bạn thích nhất là gì?',
  'Thành phố bạn sinh ra là gì?'
];

export const STAFF_LIST: User[] = [
  {
    id: 'mgr-01',
    name: 'Lê Nhật Trường',
    code: 'M001',
    abbreviation: 'LNT',
    phone: '0901234567',
    zalo: '0901234567',
    companyEmail: 'lenhattruong.tpp@gmail.com',
    personalEmail: 'nhattruong@gmail.com',
    role: 'Admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Truong',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[0],
    securityAnswer: 'Dế Mèn Phiêu Lưu Ký'
  },
  {
    id: 'mgr-tp',
    name: 'Quản Trị Viên',
    code: 'TP001',
    abbreviation: 'TP',
    phone: '0900000000',
    zalo: '0900000000',
    companyEmail: 'tanphuvietnam.tpp@gmail.com',
    personalEmail: 'tanphuvietnam.tpp@gmail.com',
    role: 'Trưởng Phòng',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[0],
    securityAnswer: 'Tan Phu'
  },
  {
    id: 'lead-01',
    name: 'Bành Nhựt Hùng',
    code: 'L001',
    abbreviation: 'BNH',
    phone: '0907654321',
    zalo: '0907654321',
    companyEmail: 'hung.banh@tanphuvietnam.vn',
    personalEmail: 'nhuthung@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hung',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[2],
    securityAnswer: 'Lu'
  },
  {
    id: 'staff-01',
    name: 'Võ Thị Mỹ Tân',
    code: '2020.00292',
    abbreviation: 'VMT',
    phone: '0912345678',
    zalo: '0912345678',
    companyEmail: 'tan.vo@tanphuvietnam.vn',
    personalEmail: 'mytan@gmail.com',
    role: 'Trưởng Nhóm',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tan',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[1],
    securityAnswer: 'Hoa'
  },
  {
    id: 'staff-02',
    name: 'Nguyễn Kiều Phan Tú',
    code: '2017.00308',
    abbreviation: 'NPT',
    phone: '0922345678',
    zalo: '0922345678',
    companyEmail: 'tu.nguyen@tanphuvietnam.vn',
    personalEmail: 'phantu@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tu',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[3],
    securityAnswer: 'Nguyễn Văn Trỗi'
  },
  {
    id: 'staff-03',
    name: 'Lê Hoàng Nam',
    code: 'S003',
    abbreviation: 'LHN',
    phone: '0932345678',
    companyEmail: 'nam.lh@company.com',
    personalEmail: 'hoangnam@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nam',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[4],
    securityAnswer: 'Phở'
  },
  {
    id: 'staff-04',
    name: 'Đặng Thu Thảo',
    code: 'S004',
    abbreviation: 'DTT',
    phone: '0942345678',
    companyEmail: 'thao.dt@company.com',
    personalEmail: 'thuthao@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Thao',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[1],
    securityAnswer: 'Lan'
  },
  {
    id: 'staff-05',
    name: 'Bùi Anh Dũng',
    code: 'S005',
    abbreviation: 'BAD',
    phone: '0952345678',
    companyEmail: 'dung.ba@company.com',
    personalEmail: 'anhdung@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dung',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[5],
    securityAnswer: 'Hà Nội'
  },
  {
    id: 'staff-06',
    name: 'Vũ Thị Lan',
    code: 'S006',
    abbreviation: 'VTL',
    phone: '0962345678',
    companyEmail: 'lan.vt@company.com',
    personalEmail: 'thilan@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lan',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[0],
    securityAnswer: 'Harry Potter'
  },
  {
    id: 'staff-07',
    name: 'Đỗ Tiến Đạt',
    code: 'S007',
    abbreviation: 'DTD',
    phone: '0972345678',
    companyEmail: 'dat.dt@company.com',
    personalEmail: 'tiendat@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dat',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[2],
    securityAnswer: 'Mimi'
  },
  {
    id: 'staff-08',
    name: 'Ngô Mỹ Linh',
    code: 'S008',
    abbreviation: 'NML',
    phone: '0982345678',
    companyEmail: 'linh.nm@company.com',
    personalEmail: 'mylinh@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Linh',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[4],
    securityAnswer: 'Bún chả'
  },
  {
    id: 'staff-09',
    name: 'Lý Gia Bảo',
    code: 'S009',
    abbreviation: 'LGB',
    phone: '0992345678',
    companyEmail: 'bao.lg@company.com',
    personalEmail: 'giabao@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bao',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[5],
    securityAnswer: 'TP.HCM'
  },
  {
    id: 'staff-10',
    name: 'Võ Tuyết Ngân',
    code: 'S100',
    abbreviation: 'VTN',
    phone: '0901239999',
    companyEmail: 'ngan.vt@company.com',
    personalEmail: 'tuyetngan@gmail.com',
    role: 'Nhân Viên',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ngan',
    status: 'ACTIVE',
    securityQuestion: SECURITY_QUESTIONS[1],
    securityAnswer: 'Mai'
  }
];
